services:
  aicodereviewfrontend:
    image: aicodereviewfrontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
